### ISSUE TITLE
Cocoapods 1.0.12 version pod error

### ISSUE THREAD

**Issue by CureleaAndrei** [vyshane/grpc-swift-combine#23]
POD:   pod 'CombineGRPC', '~> 1.0.12'

Hi, I am trying to update to version 1.0.12 using cocoapods but I get the following error:

CocoaPods could not find compatible versions for pod "CombineGRPC":
  In Podfile:
    CombineGRPC (~> 1.0.12)

None of your spec sources contain a spec satisfying the dependency: `CombineGRPC (~> 1.0.12)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 
 I am doing something wrong ? or this is a bug? Thank you!

**Comment by vyshane** [comment]
Unfortunately upstream grpc-swift have not updated their podspec since [1.6.0](https://github.com/grpc/grpc-swift/blob/main/gRPC-Swift.podspec#L5). Therefore, the latest version of CombineGRPC that is available in Cocoapods is [1.0.8](https://github.com/vyshane/grpc-swift-combine/releases/tag/1.0.8), and that matches v1.6.0 of grpc-swift.

**Comment by CureleaAndrei** [comment]
Hi, I'm back. Using the SPM worked, but in my case I couldn't used it inside the private Pod (build using cocoapods) that I am developing. I will close this issue, hopping it will be fixed when the grpc-swift updates their podspec. Thanks for the fast reply! Keep up the good work.
